services:
  mlr-auto:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads:rw
      - ./outputs:/app/outputs:rw
      - ./static:/app/static:ro
      - ./templates:/app/templates:ro
      - ./utils:/app/utils:ro
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - SESSION_SECRET=${SESSION_SECRET:-your-secret-key-change-this-in-production}
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - PORT=5000
      - MAX_CONTENT_LENGTH=209715200
    restart: unless-stopped
    container_name: mlr-automation
    networks:
      - mlr-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp:noexec,nosuid,size=100m

networks:
  mlr-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  uploads:
    driver: local
  outputs:
    driver: local